### PR TITLE
Requests

### PR DESCRIPTION
**Pull request by the01**
Pull request (including latest master)

### CODE REVIEW

**Comment by KurochkinVasiliy** [comment]
After renaming several classes it has conflicts with master branch

**Comment by the01** [comment]
Should merge now without problems.
Please check if I've missed something though.

btw. you can change the project description with this pull request from
"theoldreader api wrapper(python 3.3) "
to just
"theoldreader api wrapper"
;)

**Comment by KurochkinVasiliy** [comment]
Hi!
There is one problem in code.

in connection.make_request() you has this strings
        return response.json()

but when you use something like mark_as_starred() you will get +b'OK' response and when you try responce.join() you will get an error.

I will use this
        try:
            result = response.json()
        except ValueError:
            result = None
        return result

**Comment by KurochkinVasiliy** [comment]
I will merge it and manualy change master branch.
pls dont forget to change it in your fork

**Comment by the01** [comment]
> Hi!
> There is one problem in code.
> 
> in connection.make_request() you has this strings
> return response.json()
> 
> but when you use something like mark_as_starred() you will get +b'OK' response and when you try responce.join() you will get an error.
> 
> I will use this
> try:
> result = response.json()
> except ValueError:
> result = None
> return result

You might also consider

``` python
try:
  result = response.json()
except ValueError:
  result = response.text
return result
```

So it first tries to interpret it as json and if that fails as text

P.s.

> I will merge it and manualy change master branch.
> pls dont forget to change it in your fork

That's the beauty of git, I don't need to. Just have to do a quick git pull :wink:

**Pull request merged**
